// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAutr1ayxXC8c1gIKhe7wUvjWllqrwq7J8',
    appId: '1:310974955961:web:c4d7d05ad1d1fd0464f668',
    messagingSenderId: '310974955961',
    projectId: 'flutter-project-75d06',
    authDomain: 'flutter-project-75d06.firebaseapp.com',
    storageBucket: 'flutter-project-75d06.appspot.com',
    measurementId: 'G-0LT5R6D120',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO3aNBGXjJA6uXTMvF02MUhWsVkY5S0UU',
    appId: '1:310974955961:android:585b9e25ad23d25964f668',
    messagingSenderId: '310974955961',
    projectId: 'flutter-project-75d06',
    storageBucket: 'flutter-project-75d06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB194HOA0cckKi2ZA3eaTi-UvOKF58MnGY',
    appId: '1:310974955961:ios:c0b0f8fcdfe7217864f668',
    messagingSenderId: '310974955961',
    projectId: 'flutter-project-75d06',
    storageBucket: 'flutter-project-75d06.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB194HOA0cckKi2ZA3eaTi-UvOKF58MnGY',
    appId: '1:310974955961:ios:a04079825f1a038e64f668',
    messagingSenderId: '310974955961',
    projectId: 'flutter-project-75d06',
    storageBucket: 'flutter-project-75d06.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
